#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2025 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
#--------------------------------------------------------------------------------

SCRIPT=`basename $0`

USAGE="
Usage: $SCRIPT username password
       $SCRIPT -h

       username = the user name
       password = the user password
"

#--------------------------------------------------------------------------------
# Initialize script with common definitions

INIT_FILE=`dirname $0`/lib/init_admin_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

USERNAME="$1"
PASSWORD="$2"

if [ "$USERNAME" = "" -o "$PASSWORD" = "" ]; then
    echo "$USAGE"
    exit 1
fi

#--------------------------------------------------------------------------------

echo "Testing user login for $USERNAME provided password ..."

RESULT=$(testUserLogin "$USERNAME" "$PASSWORD")

if [ "$RESULT" = "NOK" ]; then
    errorExit "Login failed for user $USERNAME using the specified password"
fi

echoAndLog "Login succeeded for $USERNAME using the specified password"

addToLog "DONE"
