#!/bin/bash


IDA_ROOT="/usr/local/fd/ida-fairdata-v3"

if [ ! -d "$IDA_ROOT" ]; then
    IDA_ROOT="/var/ida"
fi

if [ ! -d "$IDA_ROOT" ]; then
    echo "Error: IDA root directory not found."
    exit 1
fi  

TRANSLATIONS_FILE="$IDA_ROOT/nextcloud/apps/ida/src/l10n/translations.json"

# Build full strings list
cat $IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/*_strings.txt | sort -u > /tmp/$$.strings.txt

# Extract keys from the JSON file
jq -r 'keys[]' "$TRANSLATIONS_FILE" > /tmp/$$.translations_keys.txt

# Find strings in the first file that are not in the keys of the JSON dictionary
grep -Fxvf /tmp/$$.translations_keys.txt /tmp/$$.strings.txt > $IDA_ROOT/nextcloud/apps/ida/src/l10n/utils/missing_translation_strings.txt

# Output the result
echo "Strings not found in '$TRANSLATIONS_FILE' saved in 'missing_translation_strings.txt'."

# Cleanup
rm /tmp/$$.strings.txt
rm /tmp/$$.translations_keys.txt

