#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
#--------------------------------------------------------------------------------
# This script will take a user name as an argument, retrieve a password from the
# environment variable OC_PASS and execute a forced local login for the user, which
# activates the user account such that Nextcloud will not invalidate app passwords
# after 5 minutes due to the user never having logged in with a password, only via
# the SSO, which doesn't use the Nextcloud password.
#--------------------------------------------------------------------------------

. `dirname $0`/../lib/init_script.sh

USAGE="Usage: $SCRIPT user_name"

if [ $# -ne 1 ]; then
	echo "$USAGE" >&2
    exit 1
fi

USER="$1"

if [ "$OC_PASS" = "" ]; then
	echo "No new password, OC_PASS is empty, user: $USER" >&2
    exit 1
fi

echoAndLog "Forcing local login for user $USER"

HOSTNAME=`hostname`

OUT=`curl -I -S -s -u "${USER}:${OC_PASS}" -w "%{http_code}" -o /dev/null "https://${HOSTNAME}/remote.php/dav/files/${USER}/"`

if [ "$OUT" != "200" ]; then
    errorExit "Failed to login to Nextcloud as user ${USER}: ${OUT}"
fi

echoAndLog "Successfully forced local login for user $USER"
