#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2020 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------
# This script audits the specified project in the IDA service, limited to nodes
# created or modified before the start of the auditing process.
#
# The script directly queries the database tables and filesystems, and it is
# not necessary for Apache/Nextcloud/IDA to be running in order to execute this
# script; only the database needs to be running.
# --------------------------------------------------------------------------------

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT PROJECT [OPTIONS]
       $SCRIPT -h

       OPTIONS:

       --full
       --changed-after  DATE[TIME] 
       --changed-before DATE[TIME] 
       (--staging|--frozen) 
       --timestamps 
       --checksums 
       (--report|--report-errors) [EMAIL] 
       --error-file ERROR_FILE

       Where:

       PROJECT          the project to be audited
       --full           full audit, implies --timestamps --checksums and none of --changed-* --staging --frozen
       --changed-after  auditing will be limited to project data changes after the specified date[time]
       --changed-before auditing will be limited to project data changes before the specified date[time]
       DATE[TIME]       an ISO date or datetime string /YYYY-MM-DD(Thh:mm:ssZ])?/
       --staging        auditing will be limited to files in the staging area
       --frozen         auditing will be limited to files in the frozen area
       --timestamps     comparisons will be made between disk timestamps and database values
       --checksums      comparisons will be made between new filesystem checksum and recorded cache, IDA, and Metax checksums
       --report         auditing results will be emailed
       --report-errors  auditing results will be emailed, but only if errors are detected
       EMAIL            the email address where audit reports should be sent (defaults to configured recipient list)
       ERROR_FILE       the pathname of the audit error file to be loaded

If --changed-after and/or --changed-before are specified, files and folders which are outside the scope of files
uploaded or frozen during the specified period, including changes only occurring in the filesystem and not known
to Nextcloud, will not not be included in the audit; only changes which can be identified by timestamp updates in
the Nextcloud or Metax databases which are within than the specified time period will be audited. To detect
filesystem only changes you must perform an unrestricted audit without specifying any --changed-* parameters.

If an audit error file is specified, then the new audit is limited only to files referenced in the audit error file.
"

# --------------------------------------------------------------------------------

INIT_FILE=`dirname "$(realpath $0)"`/lib/init_audit_script.sh

if [ -e $INIT_FILE ]
then
    sleep 1 # ensure a unique START timestamp for each audit
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting."
    exit 1
fi

SNAIL=`mail --version 2>/dev/null | grep -- 's-nail' 2>/dev/null`

if [ ! -d "$PROJECT_STORAGE_OC_DATA_ROOT" ]; then
    errorExit "The specified project ${PROJECT} does not exist"
fi

#--------------------------------------------------------------------------------
# Process command line arguments...

shift # got PROJECT from first argument via init_audit_script.sh

while [ "$1" ]; do

    case "$1" in
        "--full")
            if [ "$AFTER" ]; then
                echo "Only one of --full or --changed-after is allowed" >&2
                exit 1
            fi
            if [ "$BEFORE" ]; then
                echo "Only one of --full or --changed-before is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_STAGING" ]; then
                echo "Only one of --full or --staging is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_FROZEN" ]; then
                echo "Only one of --full or --frozen is allowed" >&2
                exit 1
            fi
            if [ "$ERROR_FILE" ]; then
                echo "Only one of --full or --error-file is allowed" >&2
                exit 1
            fi
            FULL_AUDIT="true"
            ;;
        "--changed-after")
            if [ "$FULL_AUDIT" = "true" ]; then
                echo "Only one of --changed-after or --full is allowed" >&2
                exit 1
            fi
            if [ "$ERROR_FILE" ]; then
                echo "Only one of --changed-after or --error-file is allowed" >&2
                exit 1
            fi
            if [ -z "$2" ]; then
                echo "Missing date[time] argument" >&2
                exit 1
            fi
            if [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
                AFTER="$2"
            elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
                AFTER="$2""T00:00:00Z"
            else
                echo "Invalid date[time]: $2" >&2
                exit 1
            fi
            shift
            ;;
        "--changed-before")
            if [ "$FULL_AUDIT" = "true" ]; then
                echo "Only one of --changed-before or --full is allowed" >&2
                exit 1
            fi
            if [ "$ERROR_FILE" ]; then
                echo "Only one of --changed-before or --error-file is allowed" >&2
                exit 1
            fi
            if [ -z "$2" ]; then
                echo "Missing date[time] argument" >&2
                exit 1
            fi
            if [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}T[[:digit:]]{2}:[[:digit:]]{2}:[[:digit:]]{2}Z$ ]]; then
                BEFORE="$2"
            elif [[ "$2" =~ ^[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}$ ]]; then
                BEFORE="$2""T00:00:00Z"
            else
                echo "Invalid date[time]: $2" >&2
                exit 1
            fi
            shift
            ;;
        "--staging")
            if [ "$FULL_AUDIT" = "true" ]; then
                echo "Only one of --full or --staging is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_FROZEN" ]; then
                echo "Only one of --staging or --frozen is allowed" >&2
                exit 1
            fi
            if [ "$ERROR_FILE" ]; then
                echo "Only one of --error-file or --staging is allowed" >&2
                exit 1
            fi
            AUDIT_STAGING="true"
            ;;
        "--frozen")
            if [ "$FULL_AUDIT" = "true" ]; then
                echo "Only one of --full or --frozen is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_STAGING" ]; then
                echo "Only one of --staging or --frozen is allowed" >&2
                exit 1
            fi
            if [ "$ERROR_FILE" ]; then
                echo "Only one of --error-file or --frozen is allowed" >&2
                exit 1
            fi
            AUDIT_FROZEN="true"
            ;;
        "--timestamps")
            if [ "$ERROR_FILE" ]; then
                echo "Only one of --timestamps or --error-file is allowed" >&2
                exit 1
            fi
            AUDIT_TIMESTAMPS="true"
            ;;
        "--checksums")
            if [ "$ERROR_FILE" ]; then
                echo "Only one of --checksums or --error-file is allowed" >&2
                exit 1
            fi
            AUDIT_CHECKSUMS="true"
            ;;
        "--error-file")
            if [ "$FULL_AUDIT" = "true" ]; then
                echo "Only one of --error-file or --full is allowed" >&2
                exit 1
            fi
            if [ "$AFTER" ]; then
                echo "Only one of --error-file or --changed-after is allowed" >&2
                exit 1
            fi
            if [ "$BEFORE" ]; then
                echo "Only one of --error-file or --changed-before is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_STAGING" ]; then
                echo "Only one of --error-file or --staging is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_FROZEN" ]; then
                echo "Only one of --error-file or --frozen is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_TIMESTAMPS" ]; then
                echo "Only one of --error-file or --timestamps is allowed" >&2
                exit 1
            fi
            if [ "$AUDIT_CHECKSUMS" ]; then
                echo "Only one of --error-file or --checksums is allowed" >&2
                exit 1
            fi
            if [ ! -f "$2" ]; then
                echo "Invalid audit error file pathname: $2" >&2
                exit 1
            fi
            ERROR_FILE="$2"
            shift
            ;;
        "--report" | "--report-errors")
            if [ "$REPORT_REQ" ]; then
                echo "Only one of --report or --report-errors is allowed" >&2
                exit 1
            fi
            REPORT_REQ="${1:2}"
            ;;
        *)
            if [ "$REPORT_REQ" ] && [ -z "$RECIPIENTS" ]; then
                RECIPIENTS="$1"
            else
                echo "Invalid argument: $1" >&2
                exit 1
            fi
            ;;
    esac

    shift

done

if [ "$REPORT_REQ" ]; then
    if [ -z "$RECIPIENTS" ]; then
        RECIPIENTS="$EMAIL_RECIPIENTS"
    fi
fi

# If after timestamp not specified, use the unix epoch
if [ -z "$AFTER" ]; then
    AFTER="1970-01-01T00:00:00Z"
fi

# If before timestamp not specified, use the start time
if [ -z "$BEFORE" ]; then
    BEFORE="$START"
fi

if [[ "$AFTER" == "$START" || "$AFTER" > "$START" ]]; then
    errorExit "Specified after timestamp $AFTER must be in the past"
fi

if [ "$BEFORE" != "$START" ]; then
    if [[ "$AFTER" == "$BEFORE" || "$AFTER" > "$BEFORE" ]]; then
        errorExit "Specified after timestamp $AFTER must be earlier than the specified before timestamp $BEFORE"
    fi
fi

#--------------------------------------------------------------------------------

LOG_ROOT=`dirname "$(realpath $LOG)"`
YEAR=`date -u +"%Y"`
MONTH=`date -u +"%m"`
REPORT_ROOT="${LOG_ROOT}/audits"
REPORT_BASE="${LOG_ROOT}/audits/${YEAR}/${MONTH}/${START}_${PROJECT}"

mkdir -p $REPORT_ROOT/$YEAR/$MONTH 2>/dev/null

#--------------------------------------------------------------------------------

if [ "$DEBUG" = "true" ]; then
    echo "ROOT:             $ROOT"
    echo "PROJECT:          $PROJECT"
    echo "START:            $START"
    echo "AFTER:            $AFTER"
    echo "BEFORE:           $BEFORE"
    echo "FULL_AUDIT:       $FULL_AUDIT"
    echo "AUDIT_STAGING:    $AUDIT_STAGING"
    echo "AUDIT_FROZEN:     $AUDIT_FROZEN"
    echo "AUDIT_TIMESTAMPS: $AUDIT_TIMESTAMPS"
    echo "AUDIT_CHECKSUMS:  $AUDIT_CHECKSUMS"
    echo "ERROR_FILE:       $ERROR_FILE"
    echo "REPORT_REQ:       $REPORT_REQ"
    echo "RECIPIENTS:       $RECIPIENTS"
fi

#--------------------------------------------------------------------------------

OUTPUT="/var/tmp/$$.out"
SUMMARY="$OUTPUT.summary"

source $ROOT/venv/bin/activate

export ROOT
export PROJECT
export START
export AFTER
export BEFORE
export FULL_AUDIT
export AUDIT_STAGING
export AUDIT_FROZEN
export AUDIT_TIMESTAMPS
export AUDIT_CHECKSUMS
export ERROR_FILE

python -u $ROOT/utils/appsupport/lib/audit_project.py > $OUTPUT

if [ "$?" -ne 0 ]; then
    rm $OUTPUT 2>/dev/null
    errorExit "Auditing of project $PROJECT failed"
fi

if [ $(stat -c %s "$OUTPUT") -eq 0 ]; then
    cat $OUTPUT > $REPORT_BASE
else
    jq --indent 4 < $OUTPUT > $REPORT_BASE
fi

if [ "$?" -ne 0 ]; then
    if [ -f $REPORT_BASE ]; then
        if [ -s $REPORT_BASE ]; then
            mv $OUTPUT $REPORT_BASE.err
        else
            mv $REPORT_BASE $REPORT_BASE.err
        fi
    fi
    rm $OUTPUT 2>/dev/null
    errorExit "Formatting of auditing report for project $PROJECT failed"
fi

SEND_REPORT="false"

if [ "$REPORT_REQ" = "report" ]; then
    SEND_REPORT="true"
fi

OK=`head -20 $REPORT_BASE | grep "\"invalidNodeCount\" *: *0\b"`

if [ "$OK" ]; then
   OK="true"
else
   OK="false"
fi

if [ "$OK" = "true" ]; then
    REPORT="$REPORT_BASE.OK.json"
else
    REPORT="$REPORT_BASE.ERR.json"
    if [ "$REPORT_REQ" = "report-errors" ]; then
        SEND_REPORT="true"
    fi
fi

mv $REPORT_BASE $REPORT

echo "Audit results saved to file $REPORT" 

if [ "$OK" = "true" ]; then
    jq 'del(.invalidNodes, .errors, .oldest, .newest)' --indent 4 < $REPORT > $SUMMARY
else
    jq 'del(.invalidNodes) | walk(if type == "object" then with_entries(select(.key != "nodes")) else . end)' --indent 4 < $REPORT > $SUMMARY
    cp $SUMMARY $REPORT.summary
fi

if [ "$?" -ne 0 ]; then
    errorExit "Generation of auditing report summary $REPORT failed"
fi

# Send email if specified

if [ "$DEBUG" = "true" ]; then
    echo "--- $SCRIPT ---"
    echo "REPORT:        $REPORT"
    echo "SEND_REPORT:   $SEND_REPORT"
    echo "RECIPIENTS:    $RECIPIENTS"
fi

if [ "$SEND_REPORT" = "true" ] && [ "$RECIPIENTS" ]; then

    HOSTNAME=`hostname`

    SUBJECT="Auditing report for project $PROJECT"

    if [ "$IDA_ENVIRONMENT" != "PRODUCTION" ]; then
        SUBJECT="${IDA_ENVIRONMENT} (${HOSTNAME}) ${SUBJECT}"
    fi

    if [ "$OK" = "true" ]; then
        SUBJECT="${SUBJECT} - OK"
    else
        SUBJECT="${SUBJECT} - Errors Reported"
    fi

    if [ "$SNAIL" ]; then
        # Convert comma delimited recipient lists to space delimited
        RECIPIENTS=`echo "$RECIPIENTS" | sed -e 's/,/ /g'`
        COMMAND="mail -s \"$SUBJECT\" -r $EMAIL_SENDER $RECIPIENTS"
    else
        COMMAND="mail -s \"${SUBJECT}\" -r ${EMAIL_SENDER} -S \"replyto=${EMAIL_SENDER}\" ${RECIPIENTS}"
    fi

    if [ "$DEBUG" = "true" ]; then
        echo "EMAIL_SENDER:     ${EMAIL_SENDER}"
        echo "EMAIL_RECIPIENTS: ${EMAIL_RECIPIENTS}"
        echo "SUBJECT:          ${SUBJECT}"
        echo "COMMAND:          ${COMMAND}"
    fi

    cat "$SUMMARY" | eval "$COMMAND" 2>$ERR

    if [ -s $ERR ]; then
        MSG=`cat $ERR`
        addToLog "$MSG"
        errorExit "Failed to send audit summary email"
    fi
fi

cat $SUMMARY

rm $OUTPUT 2>/dev/null
rm $SUMMARY 2>/dev/null

addToLog "DONE"
