#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2025 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=`basename $0`
USAGE="Usage: $SCRIPT [--json | --local]"
PROJECT="null"

INIT_FILE=`dirname $0`/lib/init_appsupport_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

if [ "$CSC_DATA_DELETION_MICROSERVICE" == "" ]; then
    errorExit "The variable CSC_DATA_DELETION_MICROSERVICE is not defined in the configuration. Aborting." >&2
fi

JSON=$(echo "$*" | grep -w -- '--json')
LOCAL=$(echo "$*" | grep -w -- '--local')

#--------------------------------------------------------------------------------

if [ "$LOCAL" ]; then

    if [ "$JSON" ]; then
        errorExit "The --json parameter cannot be used with the --local parameter" >&2
    fi

    find -L /mnt/storage_vol01/ida -mindepth 3 -maxdepth 3 -type f -name PRESERVED | sed -e 's/.*\/PSO_//' | sed -e 's/\/files.*$//'

else

    OUT=$($CURL_GET "$CSC_DATA_DELETION_MICROSERVICE/projects?services=IDA&states=datapreserved&open=false" 2>$ERR)

    if [ -s $ERR ]; then
        MSG=`cat $ERR`
        addToLog "$MSG"
        echo "$MSG" >&2
        errorExit "Failed to retrieve projects from microservice"
    fi

    if [ "$JSON" ]; then
        echo "$OUT" | jq --indent 4 '.'
    else
        echo "$OUT" | jq '.[] | .number' --raw-output | sort -u
    fi
fi

addToLog "DONE"
