#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2025 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT PROJECT [--json]
       $SCRIPT -h

       PROJECT    the project name
       --json     output file details as JSON
"

#--------------------------------------------------------------------------------
# Initialize script with common definitions

INIT_FILE=`dirname $0`/lib/init_appsupport_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

JSON=$(echo "$*" | grep -- "--json")

if [ "JSON" ]; then
    FIELDS="storage_identifier,pathname,published"
else
    FIELDS="pathname"
fi

OUT=$($CURL_GET -H "$METAX_AUTH_HEADER" "$METAX_API/files?csc_project=${PROJECT}&fields=${FIELDS}&published=true&pagination=false")

if [ -s $ERR ]; then
    MSG=`cat $ERR`
    errorExit "Query to Metax failed: $MSG"
fi

if [ "$JSON" ]; then
    echo "$OUT" | jq --indent 4
else
    echo "$OUT" | jq -r 'if type=="array" then .[] | .pathname else empty end' | sort -u
fi

addToLog "DONE"
