#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2018 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
#--------------------------------------------------------------------------------
#
# Run this script every time the Nextcloud codebase is updated
# when pulling from the GitHub repository, to ensure that all
# ownership and permissions are correct (as they can sometime
# change during update, even if rarely).
#
#--------------------------------------------------------------------------------
# Ensure script is run as root

ID=$(id -u -n)
if [ "$ID" != "root" ]; then
    sudo "$0" "$@"
    exit
fi

#--------------------------------------------------------------------------------
# Load configuration

CONFIG_FILE=$(dirname $(realpath "$0"))/../config/config.sh

if [ -e $CONFIG_FILE ]
then
    source $CONFIG_FILE
else
    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

if [ "$IDA_ENVIRONMENT" = "DEV" ]; then
    PERMS="go+rwX"
else
    PERMS="g+rwX,o-rwx"
fi

sudo chown -R -P apache:apache $ROOT
sudo chown apache:apache $ROOT/config/config.sh
sudo chown apache:apache $ROOT/nextcloud/config/config.php

sudo chmod +x $ROOT/nextcloud/occ
sudo chmod +x $ROOT/agents/replication/dmfstatus
sudo chmod +x $ROOT/agents/replication/mock_dmfstatus
sudo chmod +x $ROOT/agents/replication/mock_dmfstatus_timeout

sudo chmod -R $PERMS $ROOT
sudo chmod $PERMS $ROOT/config/config.sh
sudo chmod $PERMS $ROOT/nextcloud/config/config.php
