#!/usr/bin/env bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2020 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------
# Ensure script is run as apache

ID=$(id -u -n)
if [ "$ID" != "apache" ]; then
    sudo -u apache "$0" "$@"
    exit
fi

#--------------------------------------------------------------------------------

SCRIPT_PATHNAME="$(realpath $0)"
UTILS=$(dirname "$SCRIPT_PATHNAME")
ROOT=$(dirname "$UTILS")

if [ ! -f "$ROOT/config/config.sh" ]; then
    echo "Could not find configuration file" >&2
    exit 1
fi

source $ROOT/config/config.sh

# Only use the core os versions of commands
    
PATH="/usr/bin:/bin:/usr/sbin:/sbin"
export PATH

# Ensure the required version of python exists

PYTHON=$(which python3.12)

if [ ! -x "$PYTHON" ]; then
    echo "Could not find python executable" >&2
    exit 1
fi

#--------------------------------------------------------------------------------

rm -fr $ROOT/venv 2>/dev/null

$PYTHON -m venv $ROOT/venv

source $ROOT/venv/bin/activate

pip install --no-cache-dir --upgrade pip
pip install --no-cache-dir -r $ROOT/requirements.txt
