#!/bin/bash
#--------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
#--------------------------------------------------------------------------------
# This script will configure Nextcloud to use a cronjob for housekeeping and will
# configure that cronjob to be executed regularly.
#--------------------------------------------------------------------------------
# Ensure script is run as root

ID=$(id -u -n)
if [ "$ID" != "root" ]; then
    sudo "$0" "$@"
    exit
fi

#--------------------------------------------------------------------------------

SCRIPT_PATHNAME="$(realpath $0)"
UTILS=$(dirname "$SCRIPT_PATHNAME")
ROOT=$(dirname "$UTILS")

CONSTANTS_FILE="$ROOT/lib/constants.sh"

if [ -e $CONSTANTS_FILE ]
then
    source $CONSTANTS_FILE
else
    echo "The service constants file $CONSTANTS_FILE cannot be found. Aborting." >&2
    exit 1
fi

CONFIG_FILE="$ROOT/config/config.sh"

if [ -e $CONFIG_FILE ]
then
    source $CONFIG_FILE
else
    echo "The configuration file $CONFIG_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------

echo "Enabling cron background jobs in Nextcloud ..."
sudo -u apache $ROOT/nextcloud/occ config:app:set core backgroundjobs_mode --value="cron"

echo "Configuring Nextcloud cron job in /etc/cron.d ..."
echo "*/5  *  *  *  * apache php -f $ROOT/nextcloud/cron.php" > /etc/cron.d/nextcloud
systemctl restart crond
