#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------
# This script will query the CSC Data Deletion Process microservice to obtain a
# list of all projects which are closed and have either a grace or deletedata
# substate, and then will suspend each project which is not yet suspended and
# will delete each project which has a deletedata substate.
#
# Internal projects and projects which do not exist in IDA are skipped.
#
# It is expected that this script will be executed nightly.
#
# NOTE: If any MOCK_*_PROJECTS environment variables are defined, e.g. set by
# testing, then they will override obtaining such project lists from the actual
# environment.
# --------------------------------------------------------------------------------

SCRIPT=$(basename $0)
USAGE="Usage: $SCRIPT"
PROJECT="null"

INIT_FILE=$(dirname $0)/lib/init_appsupport_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

export EMAIL_SENDER
export EMAIL_RECIPIENTS

#--------------------------------------------------------------------------------

if [ "$MOCK_GRACE_PROJECTS" ]; then
    GRACE_PROJECTS="$MOCK_GRACE_PROJECTS"
else
    echo "Retrieving list of projects with a CSC data deletion process substate 'grace'..."
    GRACE_PROJECTS=$($ROOT/appsupport/list-grace-projects 2>$ERR)
    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        addToLog "$MSG"
        errorExit "Failed to retrieve grace projects"
    fi
fi

if [ "$MOCK_DELETEDATA_PROJECTS" ]; then
    DELETEDATA_PROJECTS="$MOCK_DELETEDATA_PROJECTS"
else
    echo "Retrieving list of projects with a CSC data deletion process substate 'deletedata'..."
    DELETEDATA_PROJECTS=$($ROOT/appsupport/list-deletedata-projects 2>$ERR)
    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        addToLog "$MSG"
        errorExit "Failed to retrieve deletedata projects"
    fi
fi

if [ "$MOCK_SUSPENDED_PROJECTS" ]; then
    SUSPENDED_PROJECTS="$MOCK_SUSPENDED_PROJECTS"
else
    echo "Retrieving list of projects which are already suspended..."
    SUSPENDED_PROJECTS=$($ROOT/appsupport/list-suspended-projects 2>$ERR)
    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        addToLog "$MSG"
        errorExit "Failed to retrieve suspended projects"
    fi
fi

if [ "$MOCK_INTERNAL_PROJECTS" ]; then
    INTERNAL_PROJECTS="$MOCK_INTERNAL_PROJECTS"
else
    echo "Retrieving list of projects which are internal..."
    INTERNAL_PROJECTS=$($ROOT/appsupport/list-internal-projects 2>$ERR)
    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        addToLog "$MSG"
        errorExit "Failed to retrieve internal projects"
    fi
fi

for PROJECT in $GRACE_PROJECTS; do

    IS_INTERNAL=$(echo "$INTERNAL_PROJECTS" | grep -w "$PROJECT")

    if [ "$IS_INTERNAL" ]; then
        echo "Project ${PROJECT} is internal (skipped)"
        continue
    fi

    if [ -z "$MOCK_GRACE_PROJECTS" ]; then
        if [ ! -d "${STORAGE_OC_DATA_ROOT}/${PROJECT_USER_PREFIX}${PROJECT}/files" ]; then
            echo "Project ${PROJECT} does not exist in IDA (ignored)"
            continue
        fi
    fi

    IS_SUSPENDED=$(echo "$SUSPENDED_PROJECTS" | grep -w "$PROJECT")

    if [ "$IS_SUSPENDED" ]; then
        echo "Project ${PROJECT} is already suspended"
        continue
    fi

    # Only actually suspend the project if in production, otherwise just inform about appropriate actions but do nothing

    if [ "$IDA_ENVIRONMENT" != "PRODUCTION" ]; then
        echo "Project ${PROJECT} should be suspended"
        continue
    fi

    $ROOT/appsupport/suspend-project $PROJECT --delete 2>$ERR

    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        addToLog "$MSG"
        errorExit "Failed to suspend project ${PROJECT}"
    fi

    echoAndLog "Project ${PROJECT} has been suspended"

done

for PROJECT in $DELETEDATA_PROJECTS; do

    IS_INTERNAL=$(echo "$INTERNAL_PROJECTS" | grep -w "$PROJECT")

    if [ "$IS_INTERNAL" ]; then
        echo "Project ${PROJECT} is internal (skipped)"
        continue
    fi

    if [ -z "$MOCK_DELETEDATA_PROJECTS" ]; then
        if [ ! -d "${STORAGE_OC_DATA_ROOT}/${PROJECT_USER_PREFIX}${PROJECT}/files" ]; then
            echo "Project ${PROJECT} does not exist in IDA (ignored)" >&2
            continue
        fi
    fi

    # Per the terms of service, closed projects which have published data are not deleted; rather,
    # they remain suspended and only data that is not part of any published dataset is purged, but
    # all data that is part of any published dataset is retained until the project is manually and
    # explicitly deleted.

    if [ "$MOCK_PUBLISHED_PROJECTS" ]; then
        if echo "$MOCK_PUBLISHED_PROJECTS" | grep -qw "$PROJECT"; then
            HAS_PUBLISHED_DATASETS="true"
        else
            HAS_PUBLISHED_DATASETS="false"
        fi
    else
        HAS_PUBLISHED_DATASETS=$($ROOT/appsupport/has-published-datasets "$PROJECT")
    fi

    if [ "$HAS_PUBLISHED_DATASETS" = "true" ]; then

        # Only actually preserve the project if in production, otherwise just inform about appropriate actions but do nothing

        if [ "$IDA_ENVIRONMENT" != "PRODUCTION" ]; then
            echo "Project ${PROJECT} should be preserved"
            continue
        fi

        # If project already preserved, do nothing

        if [ -f "${STORAGE_OC_DATA_ROOT}/${PROJECT_USER_PREFIX}${PROJECT}/files/PRESERVED" ]; then
            echo "Project ${PROJECT} is already preserved"
            continue
        fi

        $ROOT/appsupport/preserve-project $PROJECT 2>$ERR

        if [ -s $ERR ]; then
            MSG=$(cat $ERR | tr '\n' ' ')
            addToLog "$MSG"
            errorExit "Failed to preserve project ${PROJECT}"
        fi

        echoAndLog "Project ${PROJECT} has been preserved"

    else

        # Only actually delete the project if in production, otherwise just inform about appropriate actions but do nothing

        if [ "$IDA_ENVIRONMENT" != "PRODUCTION" ]; then
            echo "Project ${PROJECT} should be deleted"
            continue
        fi

        $ROOT/appsupport/delete-project $PROJECT 2>$ERR

        if [ -s $ERR ]; then
            MSG=$(cat $ERR | tr '\n' ' ')
            addToLog "$MSG"
            errorExit "Failed to delete project ${PROJECT}"
        fi

        echoAndLog "Project ${PROJECT} has been deleted"

    fi

done

#--------------------------------------------------------------------------------

addToLog "DONE"
