#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2023 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------

SCRIPT=`basename "$(realpath $0)"`

USAGE="
Usage: $SCRIPT PID
       $SCRIPT -h

       PID = the pid of the frozen file
"

#--------------------------------------------------------------------------------
# Initialize script with common definitions

PROJECT="null"

INIT_FILE=`dirname $0`/lib/init_appsupport_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

#--------------------------------------------------------------------------------
# Process command line arguments

if [ "$#" != 1 ]; then
    echo "$USAGE" >&2
    errorExit "Invalid number of arguments"
fi

PID="$1"

#--------------------------------------------------------------------------------

$CURL_GET -H "$METAX_AUTH_HEADER" "${METAX_API}/files?storage_service=ida&storage_identifier=${PID}&limit=1" 2>$ERR >$OUT

if [ -s $ERR ]; then
    MSG=$(cat $ERR)
    addToLog "$MSG"
    errorExit "Failed to retrieve file details in Metax"
fi

cat $OUT | jq '.results[0] // empty' --indent 4

addToLog "DONE"

