#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2025 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------
# This script will remove all unpublished data from the specified project, similar
# to the delete-project script, moving the data to a trash folder, but will not
# delete the project nor touch file records or files which belong to published
# datasets defined in Metax.
# --------------------------------------------------------------------------------

SCRIPT=$(basename $0)

USAGE="
Usage: $SCRIPT PROJECT [--force]
       $SCRIPT -h

       PROJECT = the project name
       --force = the project will be preserved regardless of its datadeletion substate or grace period
"

#--------------------------------------------------------------------------------
# Initialize script with common definitions

INIT_FILE=$(dirname $0)/lib/init_appsupport_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

export ROOT
export EMAIL_SENDER
export EMAIL_RECIPIENTS
export ECHO_TEST_EMAILS

#--------------------------------------------------------------------------------
echo "Verifying project ${PROJECT} exists..."

if [ ! -d $PROJECT_STORAGE_OC_DATA_ROOT ]; then
    errorExit "The specified project ${PROJECT} does not exist"
fi

#--------------------------------------------------------------------------------

echo "Verifying project ${PROJECT} is not already preserved..."

if [ -f $PROJECT_PRESERVED ]; then
    errorExit "The specified project ${PROJECT} is already preserved"
fi

#--------------------------------------------------------------------------------

echo "Verifying project ${PROJECT} is suspended..."
    
SUSPENDED=$($CURL_GET $ADMIN_CREDENTIALS -H "$IDA_MODE_HEADER" "$IDA_API/actions?status=suspend" 2>$ERR | \
           tr '\n' ' ' | tr '{' '\n' | grep "\"action\": *\"suspend*\"" | grep "\"project\": *\"$PROJECT\"" | \
           sed -e 's/^.*"initiated": *"//' | sed -e 's/".*$//' | sort -u | tail -1)

if [ -s $ERR ]; then
    MSG=$(cat $ERR | tr '\n' ' ')
    addToLog "$MSG"
    errorExit "Failed to retrieve pending actions for project ${PROJECT}!"
fi

if [ "$SUSPENDED" = "" ]; then
    errorExit "The specified project ${PROJECT} is not suspended"
fi

#--------------------------------------------------------------------------------

if [ "$2" != "--force" ]; then

    echo "Verifying project ${PROJECT} has CSC Data Deletion Process state 'deletedata' and is active for IDA..."

    OUT=$($CURL_GET "$CSC_DATA_DELETION_MICROSERVICE/projects?projects=$PROJECT" 2>$ERR)

    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        addToLog "$MSG"
        errorExit "Failed to retrieve details of project $PROJECT from microservice. Aborting."
    fi

    PROJECT_STATE=$(echo "$OUT" | jq '.[0].state' --raw-output 2>/dev/null)

    if [ "$PROJECT_STATE" != "deletedata" ]
    then
        errorExit "Project $PROJECT does not have a data deletion process state of 'deletedata'. Aborting."
    fi

    PROJECT_IDA=$(echo "$OUT" | jq '.[0].services[] | select(. == "IDA")' --raw-output 2>/dev/null)

    if [ "$PROJECT_IDA" != "IDA" ]
    then
        errorExit "Project $PROJECT is not active in the IDA service. Aborting."
    fi

    echo "Verifying project ${PROJECT} is past the quarantine (grace) period..."

    NOW=$(date -u +"%s")
    SECONDS=$(date -u -d "$SUSPENDED" +"%s")
    ELAPSED=$(expr $NOW - $SECONDS)

    if [ "$DEBUG" = "true" ]; then
        echo ""
        echo "Project suspended: $SUSPENDED"
        echo "Project suspended: $SECONDS seconds"
        echo "Current time:      $NOW seconds"
        echo "Elapsed time:      $ELAPSED seconds"
        echo "Quarantine period: $QUARANTINE_PERIOD seconds"
        echo ""
    fi

    if [ $ELAPSED -lt $QUARANTINE_PERIOD ]; then
        errorExit "The specified project ${PROJECT} is still within the quarantine period and cannot be preserved"
    fi

    echo "Verifying project ${PROJECT} has published datasets..."

    HAS_PUBLISHED_DATASETS=$($ROOT/appsupport/has-published-datasets "$PROJECT")

    if [ "$HAS_PUBLISHED_DATASETS" != "true" ]; then
        errorExit "The specified project ${PROJECT} has no published datasets and should be deleted, not preserved"
    fi
fi

#--------------------------------------------------------------------------------

echo "Creating project trash subfolder..."

mkdir -p $PROJECT_TRASH_DATA_ROOT 2>&1 >/dev/null

if [ ! -d $PROJECT_TRASH_DATA_ROOT ]; then
    errorExit "Failed to create project trash subfolder ${PROJECT_TRASH_DATA_ROOT}"
fi

#--------------------------------------------------------------------------------

echo "Generating listing of published project datasets..."

$ROOT/appsupport/list-published-datasets $PROJECT > "${PROJECT_STORAGE_OC_DATA_ROOT}/published-datasets"

#--------------------------------------------------------------------------------

echo "Generating listing of published project files..."

$ROOT/appsupport/list-published-files $PROJECT > "${PROJECT_STORAGE_OC_DATA_ROOT}/published-files"

#--------------------------------------------------------------------------------

echo "Moving project files from staging area to project trash..."

(
    set -euo pipefail
    # Iterate over list of all relative pathnames for all files in the staging area
    while IFS= read -r RELATIVE_PATHNAME; do
        # Move file from staging area to trash
        STAGING_PATHNAME="${PROJECT_STAGING_ROOT}${RELATIVE_PATHNAME}"
        TRASH_PATHNAME="${PROJECT_TRASH_DATA_ROOT}/${PROJECT}${STAGING_FOLDER_SUFFIX}${RELATIVE_PATHNAME}"
        TRASH_DIRNAME=$(dirname "$TRASH_PATHNAME")
        if [ ! -d "$TRASH_DIRNAME" ]; then
            mkdir -p "$TRASH_DIRNAME"
        fi
        mv -f "$STAGING_PATHNAME" "$TRASH_PATHNAME"
    done < <(cd "$PROJECT_STAGING_ROOT"; find . -type f -printf '/%P\n' || true)
)

# Remove any residual empty directories in the staging area (but not the staging area root directory)

find "$PROJECT_STAGING_ROOT" -mindepth 1 -type d -empty -delete

echo "Moving unpublished project files from frozen area to project trash..."

(
    set -euo pipefail
    # Iterate over list of all relative pathnames for all files in the frozen area, filtering out published files
    while IFS= read -r RELATIVE_PATHNAME; do
        # Record relative pathname of unpublished frozen file, for later deletion from IDA
        echo "$RELATIVE_PATHNAME" >> "${PROJECT_STORAGE_OC_DATA_ROOT}/unpublished-frozen-files"
        # Move unpublished file from frozen area to trash
        FROZEN_PATHNAME="${PROJECT_FROZEN_ROOT}${RELATIVE_PATHNAME}"
        TRASH_PATHNAME="${PROJECT_TRASH_DATA_ROOT}/${PROJECT}${RELATIVE_PATHNAME}"
        TRASH_DIRNAME=$(dirname "$TRASH_PATHNAME")
        if [ ! -d "$TRASH_DIRNAME" ]; then
            mkdir -p "$TRASH_DIRNAME"
        fi
        mv -f "$FROZEN_PATHNAME" "$TRASH_PATHNAME"
    done < <(cd "$PROJECT_FROZEN_ROOT"; find . -type f -printf '/%P\n' | grep -Fv -f "${PROJECT_STORAGE_OC_DATA_ROOT}/published-files" || true)
)

# Remove any residual empty directories in the frozen area (but not the frozen area root directory)

find "$PROJECT_FROZEN_ROOT" -mindepth 1 -type d -empty -delete

#--------------------------------------------------------------------------------

echo "Marking unpublished frozen files as removed in IDA and Metax..."

# NOTE: We ignore errors if any PID doesn't correspond to a frozen file, as the desired
# end result is still achieved, that any unpublished frozen file known to IDA and/or 
# Metax is marked as removed, or at least not known as an active frozen file.

# Iterate over list of PIDs for all unpublished frozen files
while IFS= read -r UNPUBLISHED_FILE_PID; do
    $ROOT/appsupport/remove-file-from-ida "$PROJECT" "$UNPUBLISHED_FILE_PID" 2>$ERR
    if [ -s $ERR ]; then
            MSG=$(cat $ERR | tr '\n' ' ')
            echo "Error: $MSG (ignored)"
    fi
    $ROOT/appsupport/remove-file-from-metax "$UNPUBLISHED_FILE_PID" 2>$ERR
    if [ -s $ERR ]; then
            MSG=$(cat $ERR | tr '\n' ' ')
            echo "Error: $MSG (ignored)"
    fi
done < <($ROOT/appsupport/fetch-project-inventory $PROJECT --frozen --unpublished-only | jq -r '.frozen[]? | .pid? // empty')

#--------------------------------------------------------------------------------

echo "Cleaning up Nextcloud file cache..."

$ROOT/appsupport/rescan-project "$PROJECT"

#--------------------------------------------------------------------------------

MESSAGE="Project ${PROJECT} preserved. Unpublished project data copied to trash subfolder ${PROJECT_TRASH_DATA_ROOT}"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

echo "$TIMESTAMP $MESSAGE" > "${PROJECT_STORAGE_OC_DATA_ROOT}/PRESERVED"

echoAndLog "$MESSAGE"

#--------------------------------------------------------------------------------

echo "Reporting data preserved for project..."

$ROOT/appsupport/report-datapreserved $PROJECT 2>$ERR

if [ -s $ERR ]; then
    MSG=$(cat $ERR | tr '\n' ' ')
    addToLog "$MSG"
    SUBJECT="Failed to report data preserved for project ${PROJECT}!"
    MESSAGE="
${SUBJECT}

${MSG}
"
    echoAndLog "Error: ${SUBJECT} (ignored)"
    $ROOT/appsupport/email-appsupport "$SUBJECT" "$MESSAGE" 2>$ERR
    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        echoAndLog "$MSG"
    fi
fi

#--------------------------------------------------------------------------------

echo "Sending email to project users..."

SUBJECT="Project ${PROJECT} has been removed from the IDA service" 

MESSAGE="
You are a member of the CSC project ${PROJECT}, which has had rights to use the IDA service.

The project has been REMOVED from the IDA service in accordance with the official CSC Data Deletion Policy (https://docs.csc.fi/accounts/how-to-manage-your-project/#project-closure).

All unpublished project data has been DELETED from the IDA service.

All published project data (included in one or more published datasets which are openly available, under embargo, or accessible to logged-in users through Etsin) will REMAIN in the IDA service to ensure long-term accessibility of the published datasets, until otherwise agreed with the organization's IDA contact person.

If you wish to have any published project data deleted, or have any questions about the retention of published project data, please contact your home organization’s IDA contact person (https://wiki.eduuni.fi/x/FWmLGw).

If you have any other questions, please contact the CSC Service Desk (servicedesk@csc.fi).
"

$ROOT/appsupport/email-project-users "$PROJECT" "$SUBJECT" "$MESSAGE" 2>$ERR

if [ -s $ERR ]; then
    MSG=$(cat $ERR | tr '\n' ' ')
    addToLog "$MSG"
    errorExit "Failed to email project ${PROJECT} users!"
fi

#--------------------------------------------------------------------------------

echo "Generating listing of published project datasets after pruning..."

$ROOT/appsupport/list-published-datasets $PROJECT > "${PROJECT_STORAGE_OC_DATA_ROOT}/published-datasets.check"

#--------------------------------------------------------------------------------

echo "Generating listing of published project files after pruning..."

$ROOT/appsupport/list-published-files $PROJECT > "${PROJECT_STORAGE_OC_DATA_ROOT}/published-files.check"

#--------------------------------------------------------------------------------

echo "Verifying all published data remains unchanged..."

DIFF1=$(diff -U0 --suppress-common-lines "${PROJECT_STORAGE_OC_DATA_ROOT}/published-datasets" "${PROJECT_STORAGE_OC_DATA_ROOT}/published-datasets.check" | wc -l)
DIFF2=$(diff -U0 --suppress-common-lines "${PROJECT_STORAGE_OC_DATA_ROOT}/published-files" "${PROJECT_STORAGE_OC_DATA_ROOT}/published-files.check" | wc -l)

if [ "${DIFF1}${DIFF2}" != "00" ]; then
    SUBJECT="Error: Published data for preserved project ${PROJECT} has been unexpectedly affected!"
    MESSAGE="
${SUBJECT}

Published dataset listing differences: ${DIFF1}
Published file listing differences:    ${DIFF2}
"
    $ROOT/appsupport/email-appsupport "$SUBJECT" "$MESSAGE" 2>$ERR
    if [ -s $ERR ]; then
        MSG=$(cat $ERR | tr '\n' ' ')
        echoAndLog "$MSG"
    fi

    errorExit "$SUBJECT"
fi

rm -f "${PROJECT_STORAGE_OC_DATA_ROOT}/published-datasets.check" 2>/dev/null
rm -f "${PROJECT_STORAGE_OC_DATA_ROOT}/published-files.check" 2>/dev/null

#--------------------------------------------------------------------------------

addToLog "DONE"
