#!/bin/bash
# --------------------------------------------------------------------------------
# This file is part of the Fairdata IDA research data storage service.
#
# Copyright (C) 2019 Ministry of Education and Culture, Finland
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# @author   CSC - IT Center for Science Ltd., Espoo Finland <servicedesk@csc.fi>
# @license  GNU Affero General Public License, version 3
# @link     https://www.fairdata.fi/en/ida
# --------------------------------------------------------------------------------
# Initialize script with common definitions

SCRIPT=$(basename $0)
USAGE="Usage: $SCRIPT"
PROJECT="null"

INIT_FILE=$(dirname $0)/lib/init_appsupport_script.sh

if [ -e $INIT_FILE ]
then
    . $INIT_FILE
else
    echo "The initialization file $INIT_FILE cannot be found. Aborting." >&2
    exit 1
fi

SNAIL=$(mail --version 2>/dev/null | grep -- 's-nail' 2>/dev/null)

#--------------------------------------------------------------------------------

SUBJECT="[IDA Service] Failed Actions Report"
        
if [ "$IDA_ENVIRONMENT" != "PRODUCTION" ]; then
    SUBJECT="${IDA_ENVIRONMENT} (${HOSTNAME}) ${SUBJECT}"
fi

ACTIONS=$(DEBUG=false $ROOT/appsupport/fetch-actions failed 2>/dev/null)

COUNT=$(echo "$ACTIONS" | jq 'length')

if [ "$COUNT" -gt 0 ]; then

    if [ "$EMAIL_RECIPIENTS" ]; then

        if [ "$SNAIL" ]; then
            # Convert comma delimited recipient lists to space delimited
            EMAIL_RECIPIENTS=$(echo "$EMAIL_RECIPIENTS" | sed -e 's/,/ /g')
            COMMAND="mail -s \"$SUBJECT\" -r $EMAIL_SENDER $EMAIL_RECIPIENTS"
        else
            COMMAND="mail -s \"${SUBJECT}\" -r ${EMAIL_SENDER} -S \"replyto=${EMAIL_SENDER}\" ${EMAIL_RECIPIENTS}"
        fi

        if [ "$DEBUG" = "true" ]; then
            echo "EMAIL_SENDER:     ${EMAIL_SENDER}"
            echo "EMAIL_RECIPIENTS: ${EMAIL_RECIPIENTS}"
            echo "SUBJECT:          ${SUBJECT}"
            echo "ACTIONS:          ${ACTIONS}"
            echo "COMMAND:          ${COMMAND}"
        fi

        TMP_MSG=$(mktemp /tmp/ida_mail.XXXXXX)

        echo "$ACTIONS" > "$TMP_MSG"

        eval "$COMMAND < \"$TMP_MSG\"" 2>$ERR

        EXIT_STATUS=$?

        if [ $EXIT_STATUS -ne 0 ] || [ -s "$ERR" ]; then
            addToLog "Mail command exited with code $EXIT_STATUS"
            if [ -s $ERR ]; then
                MSG=$(cat $ERR)
                addToLog "$MSG"
            fi
            addToLog "Message body retained in ${TMP_MSG}"
            errorExit "Failed to send failed action report email"
        fi

        rm -f "$TMP_MSG"

        echoAndLog "${COUNT} failed actions reported"
    fi
else
    echoAndLog "No failed actions"
fi

addToLog "DONE"
