#!/bin/bash
#
# This script will perform the core of the data migration from the old to the new database. 

SCRIPT_PATHNAME="$(realpath $0)"
UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
INIT_FILE="$UPDATE_ROOT/init.sh"

if [ ! -f "$INIT_FILE" ]; then
    echo "ERROR: Could not find file $INIT_FILE"
    exit 1
fi

source "$INIT_FILE"

set -e # if anything fails, die die die

echo "--- Migrating all data from $DBNAME_OLD to $DBNAME ..."

$UPDATE_ROOT/export-data-from-old-database
$UPDATE_ROOT/validate-exported-data
$UPDATE_ROOT/import-data-into-new-database
$UPDATE_ROOT/update-sequences
$UPDATE_ROOT/update-indices
$UPDATE_ROOT/wait-for-database-housekeeping

echo "Migration completed."
