#!/bin/bash
#
# This script will rescan files to update the file cache (as an extra safety step), and
# clean up the file cache, removing any orphan entries, etc. 
#
# If running in the sandbox with a configured environment other than DEV, such that the
# database is populated with data from either PRODUCTION or DEMO, this script should not
# be run as it will corrupt the file cache since the project data does not actually exist on
# disk even though the original production file cache records have been copied to the new
# database.

SCRIPT_PATHNAME="$(realpath $0)"
UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
INIT_FILE="$UPDATE_ROOT/init.sh"

if [ ! -f "$INIT_FILE" ]; then
    echo "ERROR: Could not find file $INIT_FILE"
    exit 1
fi

source "$INIT_FILE"

if [ "$IDA_ENVIRONMENT" != "DEV" ]; then
    HOST_DOMAIN=$(hostname -f)
    if [[ "$HOST_DOMAIN" == *.fd-sandbox.csc.fi ]]; then
        echo "Error: This script should only be run in a DEV environment in the sandbox ($HOST_DOMAIN). Exiting."
        exit 1
    fi
fi

echo "--- Cleaning file cache ..."
$OCC files:cleanup

echo "--- Rescanning all data for all projects and users ..."
$OCC files:scan --all #-v

echo "--- Cleaning file cache again ..."
$OCC files:cleanup

echo "Rescan / Cleanup completed."
