#!/bin/bash
#
# This script will reset the password of the specified user to the TEST_USER_PASS value
# defined in config.sh. 

. /var/ida/config/config.sh

sudo -u apache OC_PASS="$TEST_USER_PASS" /var/ida/nextcloud/occ user:resetpassword "$1" --password-from-env
