#!/bin/bash
#
# This script will reset the password of the specified user to the TEST_USER_PASS value
# defined in config.sh. 

SCRIPT_PATHNAME="$(realpath $0)"
UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
ROOT=$(dirname "$UPDATE_ROOT")
INIT_FILE="$UPDATE_ROOT/init.sh"

if [ ! -f "$INIT_FILE" ]; then
    echo "ERROR: Could not find file $INIT_FILE"
    exit 1
fi

source "$INIT_FILE"

OC_PASS="$TEST_USER_PASS" $ROOT/nextcloud/occ user:resetpassword "$1" --password-from-env
