#!/bin/bash
#
# This script will test the full migration process in a local DEV environment but creating
# the test accounts in the new database and exporting the baseline validation data from the
# new database, rather than from the old database.
#
# If the parameter --full is given, the baseline validation data will be re-initialized and
# re-extracted, else only the post-update migration steps will be executed

mkdir "/var/ida/update/tests" 2>/dev/null

. /var/ida/update/init.sh

if [ "$IDA_ENVIRONMENT" != "DEV" ]; then
    echo "Error: This script must only be run in a DEV environment" >&2
    exit 1
fi

NEW_ONLY=$(echo "$*" | grep -- "--new-only" || true)
FULL=$(echo "$*" | grep -- "--full" || true) # legacy

if [ "$FULL" ]; then
    NEW_ONLY=""
fi

set -e 

if [ -z "$NEW_ONLY" ]; then
    /var/ida/update/reset-new-database
    /var/ida/update/extract-baseline-validation-data
    /var/ida/update/validate-baseline-data
fi

# From migrate-data
/var/ida/update/export-data-from-old-database --test
/var/ida/update/reset-new-database
/var/ida/update/import-data-into-new-database --test
/var/ida/update/update-sequences
/var/ida/update/update-indices
sudo -u apache /var/ida/utils/reset_PSO_passwords

/var/ida/update/extract-migrated-validation-data
/var/ida/update/validate-migrated-data
