#!/bin/bash
#
# This script will test the full migration process in a local DEV environment but creating
# the test accounts in the new database and exporting the baseline validation data from the
# new database, rather than from the old database.
#
# If the parameter --full is given, the baseline validation data will be re-initialized and
# re-extracted, else only the post-update migration steps will be executed

SCRIPT_PATHNAME="$(realpath $0)"
UPDATE_ROOT=$(dirname "$SCRIPT_PATHNAME")
INIT_FILE="$UPDATE_ROOT/init.sh"

if [ ! -f "$INIT_FILE" ]; then
    echo "ERROR: Could not find file $INIT_FILE"
    exit 1
fi

source "$INIT_FILE"

mkdir "$UPDATE_ROOT/tests" 2>/dev/null

set -e # if anything fails, die die die

if [ "$IDA_ENVIRONMENT" != "DEV" ]; then
    echo "Error: This script must only be run in a DEV environment" >&2
    exit 1
fi

NEW_ONLY=$(echo "$*" | grep -- "--new-only" || true)
FULL=$(echo "$*" | grep -- "--full" || true) # legacy

if [ "$FULL" ]; then
    NEW_ONLY=""
fi

if [ -z "$NEW_ONLY" ]; then
    $UPDATE_ROOT/reset-new-database
    $UPDATE_ROOT/extract-baseline-validation-data
    $UPDATE_ROOT/validate-baseline-data
fi

# Derived from migrate-data script, but with database reset and test options
$UPDATE_ROOT/export-data-from-old-database --test
$UPDATE_ROOT/validate-exported-data --test
$UPDATE_ROOT/reset-new-database
$UPDATE_ROOT/import-data-into-new-database --test
$UPDATE_ROOT/update-sequences
$UPDATE_ROOT/update-indices
$UPDATE_ROOT/wait-for-database-housekeeping
$UPDATE_ROOT/reset-reshare
$UPDATE_ROOT/extract-migrated-validation-data
$UPDATE_ROOT/validate-migrated-data
$UPDATE_ROOT/rescan-cleanup
$UPDATE_ROOT/reset-test-user-password fd_test_ida_user # for safe tests
